services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: dev
      args:
        REACT_APP_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    environment:
      REACT_APP_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: sh -c "npm start"

  backend:
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: recipes_db
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-changeme}
      JWT_SECRET: ${JWT_SECRET:-devsecret}
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npx sequelize-cli db:migrate && npm run dev"
